### ISSUE TITLE
Adding 2nd confirmation for the 'Add Row' functionality

### ISSUE THREAD

**Issue by mayurdhurpate** [FiretableProject/firetable#237]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I accidentally click "Add Row" button instead of Add Column/Hide Row/Filter. Since there is no 2nd confirmation (unlike in Firestore Console UI) and an empty row gets created, this leads to poor UX because in some cases the collection is not handled in frontend to have empty documents, which may lead to crashing of the app.

Though on the other hand, having a confirmation dialog might be a hassle for write-intensive usage for Firetable. [Should not be the case for many cases.]

**Describe the solution you'd like**
I'm not sure of the solution but 2 ideas come to my mind:
 - Having a confirm button at the start/end of the row to be tapped for the row to actually gets creates in the collection
 - On tapping Add Row, Right Sidebar may open with empty fields, and tapping "Create" button at its bottom creates a new document.

**Describe alternatives you've considered**

![image](https://user-images.githubusercontent.com/10077074/95455632-cc711800-098b-11eb-8ea7-24191c6936dc.png)

**Additional context**

**Comment by dorukde** [comment]
Hi @mayurdhurpate 
Thanks a lot for the request. 

We have been working on the empty state of the new table. in the next version: 

1. "Add Row" button will be disabled unless data is imported (or a Column is added). 
2. Also, the users will set default values for each column (to avoid empty rows by default) with the possibility to define, if the column is a required one. 
3. If any value on the row is either invalid (based on column type) or missing, there will be no changes on Firebase unless the whole column is correct. We will provide a visual feedback with red borders (and red text on required fields). Practically,  correcting the values will update. 
4. We have been discussing various ways to add new rows and they will be set next to the button.  

Thanks a lot for flagging it up.

![update](https://user-images.githubusercontent.com/20957578/95545852-bf672e00-0a4a-11eb-9d1b-8290d7401ba4.png)

**Comment by mayurdhurpate** [comment]
Wow, this is quite comprehensive! Seems perfect, especially the 3rd point.

**Comment by shamsmosowi** [comment]
released in v1.4
