### ISSUE TITLE
Should the tracking id be hardcoded?

### ISSUE THREAD

**Issue by wzulfikar** [FiretableProject/firetable#267]
When I generate a project using `firetable init`, I noticed that the ga tracking id is hardcoded in index.html.
![Screenshot 2020-11-12 at 9 16 45](https://user-images.githubusercontent.com/7823011/98907675-2a989a00-24fa-11eb-9f65-93250a09b888.jpg)

That tracking id is the same as in https://try.firetable.io.
![Screenshot 2020-11-12 at 9 17 57](https://user-images.githubusercontent.com/7823011/98907729-4603a500-24fa-11eb-9ba5-2b2ff44d798a.jpg)

My question is, is this intentional? Wouldn't it mess with your analytic for https://try.firetable.io?

**Comment by shamsmosowi** [comment]
removed
