### ISSUE TITLE
Custom emails for login

### ISSUE THREAD

**Issue by alejandrombc** [FiretableProject/firetable#272]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be great to have more alternatives to login than just google authentication. Many companies just doesnt work with gmail. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by alejandrombc** [comment]
Any news about this? 👀

**Comment by notsidney** [comment]
Hi @alejandrombc, we’ve been focused on other projects, sorry.

@shamsmosowi I think it’s about time we [switch to Firebase UI](https://github.com/firebase/FirebaseUI-Web) for our auth – seems to be really easy to set up & use, from experience

**Comment by alejandrombc** [comment]
Hi @notsidney! no problem keep your best 💪🏼.

The Firebase UI sounds really promising 👀, will wait for it!.

**Comment by alejandrombc** [comment]
Any news? 👀

**Comment by shamsmosowi** [comment]
YES! the firebase ui is now available on master, you can select the the auth options you would like to enable using the fireable project settings 
![Screen Shot 2021-07-29 at 9 50 18 pm](https://user-images.githubusercontent.com/13803906/127487234-4a5979e6-cd54-4c4a-8136-db3f573f5a1f.png)
