### ISSUE TITLE
FAILED:  Could not find account with email

### ISSUE THREAD

**Issue by serwer20** [FiretableProject/firetable#300]
**Describe the bug**
I've been trying to assign ADMIN role for the first time following this instruction:
https://github.com/AntlerVC/firetable/wiki/Role-Based-Security-Rules#set-user-roles-with-the-firetable-cli
BUT I'm always getting result like: 
`FAILED:  Could not find account with email`

**To Reproduce**
1. `firetable init [dir]`
2. `firetable start`
3. http://localhost:5000 work but I can't login because of error in left corner:
`{"error":{"code":400,"message":"API key not valid. Please pass a valid API key.","errors":[{"message":"API key not valid. Please pass a valid API key.","domain":"global","reason":"badRequest"}],"status":"INVALID_ARGUMENT"}}
`
4. `firetable auth:setRoles myemail@gmail.com ADMIN`
5. ERROR: `FAILED:  Could not find account with email`

**Expected behavior**
Command  `firetable auth:setRoles myemail@gmail.com ADMIN` should assign role to the email

**ENV :**
 - OS: Windows 10
- node     12.0.0
- git      2.29.2
- yarn     1.22.1
- firebase 9.4.0

**Additional context**
I'm also concern about my location of project which is eur3 (europe-west). I've found hardcoded `firebaseio.com` URL in `config.ts` and `credentials.ts` files which is incorrect for european location of Google datacenters.

**Comment by HieuTrLuu** [comment]
I am having the same problems

**Comment by shamsmosowi** [comment]
I think the problem is the email doesn't have a user account on firebase auth, you need to create the user in Firebase Auth before setting their roles, you can easily create user by signing into firetable for the first time, before running the command.

**Comment by shamsmosowi** [comment]
I've added functionality for prompting to creating a new account when the account doesn't exist, please make sure you're using v1.3.0 or above
