### ISSUE TITLE
REACT_APP_FIREBASE_PROJECT_WEB_API_KEY not filled by CLI

### ISSUE THREAD

**Issue by ImJustChew** [FiretableProject/firetable#375]
**Describe the bug**
REACT_APP_FIREBASE_PROJECT_WEB_API_KEY is left blank in .env and caused Firebase to not work on sign in
```
REACT_APP_FIREBASE_PROJECT_ID = *project name*
REACT_APP_FIREBASE_PROJECT_WEB_API_KEY = -
REACT_APP_ALGOLIA_APP_ID = _
REACT_APP_ALGOLIA_SEARCH_API_KEY = _
```

**To Reproduce**
1. create a firetable project with firetable init 
2. run firetable start and wait for it to build
3. Google sign in will fail due to API KEY Error

**Expected behavior**
For firetable CLI to generate the .env file with the Web API Key prefilled

**Screenshots**
Nope

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 89.0.774.48 

**Additional context**
Filling in the .env file solves the problem, but I'll have to go to www and build the project through yarn again because firetable start doesn't rebuild it.

**Comment by shamsmosowi** [comment]
Hi @ImJustChew , thanks for reporting this. I've fixed the CLI, this shouldn't be an issue anymore, please make sure you're using v1.3.0 or above
