### ISSUE TITLE
Unable to find ft_build folder

### ISSUE THREAD

**Issue by catrawalkar** [FiretableProject/firetable#435]
Hello 

I am unable to find ft_build folder any where.

https://github.com/FiretableProject/firetable/wiki/FT-Functions#setting-up-cloud-run-ft-builder

Can you help me please @shamsmosowi

**Comment by shamsmosowi** [comment]
Hi!
we are in the process of restructuring all the firetable cloud functions, so that's why it's not very documented and difficult to setup atm. ft_build is currently on the rc branch feel free to try it out. But it might change slightly in the future as we get it finalised

**Comment by shamsmosowi** [comment]
Ft_build folder is now move to separate repo to simplify the deployment process [here](https://github.com/FiretableProject/FunctionsBuilder)
