### ISSUE TITLE
Table Names / Sections are not visible on main dashboard

### ISSUE THREAD

**Issue by ncamaa** [FiretableProject/firetable#444]
**Describe the bug**
Table Names / Sections are not visible on the main dashboard aka http://localhost:5000
These tables were created using the same FT instance.

**To Reproduce**
1. Create a table using FT
2. Create some docs in the table (aka cols+rows)
3. Go to the main dashboard - http://localhost:5000
4. Table is not visible but is still accessible if you go to http://localhost:5000/table/TABLE_NAME

**Expected behavior**
The tables to be visible in the main dashboard http://localhost:5000

**Screenshots**
![image](https://user-images.githubusercontent.com/25122974/121351919-f3c21f80-c934-11eb-99f9-54d7b88de4e3.png)
Table Created

![image](https://user-images.githubusercontent.com/25122974/121351980-089eb300-c935-11eb-92df-b9cb8990e71b.png)
Table is not visible

**Desktop (please complete the following information):**
 - OSX 11.3 MacBook pro
 - Chrome / Brave

**Comment by harinij** [comment]
@ncamaa This is now fixed in the rc branch for the tables to be visible to ADMIN users by default in the main dashboard.
