### ISSUE TITLE
Documentation not clear 

### ISSUE THREAD

**Issue by zakblacki** [FiretableProject/firetable#494]
Where do we put the json file exactly ? 

'PROJECT-ID-firebase-adminsdk-ALPHANUMERIC-CHARACTERS.json' 

and `firetable auth:setRoles your_account@gmail.com` ADMIN  command is not working for me

**Comment by bofeiw** [comment]
Put it under the root path of firetable, and run the command under the same directory.

What output do you see in the console?

**Comment by zakblacki** [comment]
I'm getting 'firetable' is not recognized as an internal or external command,
operable program or batch file.

**Comment by bofeiw** [comment]
This means the firetable CLI isn't installed correctly on your local machine.

Please run `yarn global add firetable` to install it globally in your machine.

**Comment by zakblacki** [comment]
Already did that, it didn't help 
![image](https://user-images.githubusercontent.com/29728429/128213265-b9f1fe9e-3d40-400d-b119-b1a1d816cf96.png)

**Comment by bofeiw** [comment]
Yes, you need to make sure that the PATH is set correctly. Related issue: https://github.com/yarnpkg/yarn/issues/1648

**Comment by zakblacki** [comment]
Okay thanks this one resolved, but I have another issue now,  why is it empty where are my collection fields
![image](https://user-images.githubusercontent.com/29728429/128389481-24ab7e48-2c1c-4bce-9cbd-ece379eb74c9.png)

**Comment by bofeiw** [comment]
You need to click "create table" to add tables.

**Comment by zakblacki** [comment]
Where do I find the options to import my data directly ?

**Comment by bofeiw** [comment]
After you a create table, you will see the option to import columns in that table. We will add more documentation on this.
